FROM theiaide/theia:next
#   docker run -it --init -p 3000:3000 --expose 9229 -p 9229:9229 -v "$(pwd):/home/project:cached" theiaide/theia:next --inspect=0.0.0.0:9229
USER root
RUN apk add --update docker docker-compose
