name: ci-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # runs every day at 12 a.m.
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.IMAGE_NAME }}@${{ matrix.NPM_TAG }}
    runs-on: ubuntu-18.04
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        node_test: [10] # node version for the test suite.
        node: [12.18.3]
        NPM_TAG: ["latest", "next"]
        IMAGE_NAME:
          [
            "theia",
            "theia-cpp",
            "theia-full",
            "theia-go",
            "theia-https",
            "theia-php",
            "theia-python",
          ]
        include:
          - IMAGE_NAME: "theia-https"
            ENV_VARS: "-e token="
            PORT: 10443

          # `dart` images use node 12 for building.
          - IMAGE_NAME: "theia-dart"
            NPM_TAG: "latest"
            node_test: 10
            node: 12

          - IMAGE_NAME: "theia-dart"
            NPM_TAG: "next"
            node_test: 10
            node: 12

          - IMAGE_NAME: "theia-rust"
            NPM_TAG: "next"
            node_test: 10
            node: 12.18.3

          # `swift` images use node 12 for building.
          - IMAGE_NAME: "theia-swift"
            NPM_TAG: "latest"
            node_test: 10
            node: 12

          - IMAGE_NAME: "theia-swift"
            NPM_TAG: "next"
            node_test: 10
            node: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node_test }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_test }}

      - name: Lint
        shell: bash
        run: |
          npm -v
          npm install -g eclint
          eclint check "**/*" || echo "Warning! Formatting errors encountered..."

      # determine if the given image needs to be built based on changed files.
      # - builds the `theia-docker` image in the case that files not present under an `docker` folder are modified.
      # - sets the `steps.check_changed.outputs.status` environment variable which can be re-used.
      - name: Determine if ${{ matrix.IMAGE_NAME }} should be built
        id: check_changed
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          git fetch origin master:master
          RETURN_CODE=$(./check_changed.sh ${{ matrix.IMAGE_NAME }});
          if [ $RETURN_CODE -eq 137 ]; then
             echo "No changes in ${{ matrix.IMAGE_NAME }}, terminating."
             echo ::set-output name=status::'terminate'
          elif [ $RETURN_CODE -ne 0]; then
            echo "Error happened in check_changed"
            exit $RETURN_CODE;
          else
             echo ::set-output name=status::'continue'
          fi

      - name: Build
        if: github.event_name != 'pull_request' || steps.check_changed.outputs.status == 'continue'
        shell: bash
        run: ./build_container.sh ${{ matrix.NPM_TAG }} ${{ matrix.IMAGE_NAME }} ${{ matrix.node }} ${{ secrets.GITHUB_TOKEN }} ${{matrix.PORT}} ${{matrix.ENV_VARS}}

      - name: Test
        if: github.event_name != 'pull_request' || steps.check_changed.outputs.status == 'continue'
        shell: bash
        run: |
          google-chrome --version
          chromedriver --version
          (cd tests && yarn && yarn test-app-${{ matrix.IMAGE_NAME }})

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker deploy
        if: github.event_name != 'pull_request'
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          retry_on: error
          command: docker push "theiaide/${{ matrix.IMAGE_NAME }}:${{ matrix.NPM_TAG}}"
